BEGIN;
-- ====== bids ======
CREATE TABLE IF NOT EXISTS "bids" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "rider_offer_id" INTEGER;
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "bid_price" NUMERIC(10,2);
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'pending'::character varying;
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "bids" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== chat_messages ======
CREATE TABLE IF NOT EXISTS "chat_messages" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "ride_id" INTEGER;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "sender_id" VARCHAR;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "receiver_id" VARCHAR;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "read" BOOLEAN DEFAULT false;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== driver_availability ======
CREATE TABLE IF NOT EXISTS "driver_availability" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "active_mode" VARCHAR(20);
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "is_available" BOOLEAN DEFAULT false;
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "is_online_for_hire" BOOLEAN DEFAULT false;
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "current_lat" NUMERIC(10,7);
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "current_lng" NUMERIC(10,7);
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "last_location_update" TIMESTAMP;
ALTER TABLE "driver_availability" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== driver_commercial ======
CREATE TABLE IF NOT EXISTS "driver_commercial" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "is_commercial_driver" BOOLEAN DEFAULT false;
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "commercial_status_verified" BOOLEAN DEFAULT false;
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "rate_per_mile" NUMERIC(5,2);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "driver_tagline" VARCHAR(100);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "dvla_check_code" VARCHAR;
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "service_categories" TEXT[];
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "tier1_max_miles" NUMERIC(6,2);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "tier1_rate_per_mile" NUMERIC(5,2);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "tier2_max_miles" NUMERIC(6,2);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "tier2_rate_per_mile" NUMERIC(5,2);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "tier3_rate_per_mile" NUMERIC(5,2);
ALTER TABLE "driver_commercial" ADD COLUMN IF NOT EXISTS "base_minimum_fare" NUMERIC(6,2);
-- ====== driver_daily_activity ======
CREATE TABLE IF NOT EXISTS "driver_daily_activity" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_daily_activity" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "driver_daily_activity" ADD COLUMN IF NOT EXISTS "date" VARCHAR;
ALTER TABLE "driver_daily_activity" ADD COLUMN IF NOT EXISTS "rides_count" INTEGER DEFAULT 0;
ALTER TABLE "driver_daily_activity" ADD COLUMN IF NOT EXISTS "total_earnings" NUMERIC(10,2) DEFAULT '0'::numeric;
ALTER TABLE "driver_daily_activity" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_daily_activity" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== driver_documents ======
CREATE TABLE IF NOT EXISTS "driver_documents" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "document_type" VARCHAR(50);
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "document_url" VARCHAR;
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "document_number" VARCHAR;
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "expiry_date" VARCHAR;
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "uploaded_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "verified_at" TIMESTAMP;
ALTER TABLE "driver_documents" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== driver_payouts ======
CREATE TABLE IF NOT EXISTS "driver_payouts" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "ride_id" INTEGER;
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "stripe_transfer_id" VARCHAR(80);
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "amount_pence" INTEGER;
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "status" VARCHAR(30) DEFAULT 'pending'::character varying;
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "failure_reason" VARCHAR(300);
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "retry_count" INTEGER DEFAULT 0;
ALTER TABLE "driver_payouts" ADD COLUMN IF NOT EXISTS "last_attempt_at" TIMESTAMP;
-- ====== driver_profiles ======
CREATE TABLE IF NOT EXISTS "driver_profiles" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "is_driver" BOOLEAN DEFAULT false;
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "driver_verified" BOOLEAN DEFAULT false;
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "background_check_consent" BOOLEAN DEFAULT false;
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "background_check_status" VARCHAR(20);
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_profiles" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== driver_routes ======
CREATE TABLE IF NOT EXISTS "driver_routes" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "start_location" TEXT;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "end_location" TEXT;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "start_lat" NUMERIC(10,7);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "start_lng" NUMERIC(10,7);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "end_lat" NUMERIC(10,7);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "end_lng" NUMERIC(10,7);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "departure_time" TIMESTAMP;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "max_detour_miles" NUMERIC(5,2);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "available_seats" INTEGER DEFAULT 3;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "price_per_seat" NUMERIC(10,2);
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'active'::character varying;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "total_seats" INTEGER DEFAULT 3;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "payment_timeout_minutes" INTEGER DEFAULT 5;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "schedule_id" INTEGER;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "platform_fee_collected_for_ride_id" INTEGER;
ALTER TABLE "driver_routes" ADD COLUMN IF NOT EXISTS "platform_fee_collected_pence" INTEGER DEFAULT 0;
-- ====== email_verifications ======
CREATE TABLE IF NOT EXISTS "email_verifications" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "email" VARCHAR(255);
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "otp_code" VARCHAR(72);
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "verification_token" TEXT;
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "attempts" INTEGER DEFAULT 0;
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMP;
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "verified_at" TIMESTAMP;
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "email_verifications" ADD COLUMN IF NOT EXISTS "flow_type" VARCHAR(10) DEFAULT 'signup'::character varying;
-- ====== notifications ======
CREATE TABLE IF NOT EXISTS "notifications" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "type" VARCHAR(50);
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "title" VARCHAR(255);
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "read" BOOLEAN DEFAULT false;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "related_ride_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "related_offer_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "related_bid_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== org_documents ======
CREATE TABLE IF NOT EXISTS "org_documents" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "org_id" INTEGER;
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "document_type" VARCHAR(50);
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "document_url" VARCHAR;
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "file_name" VARCHAR(255);
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "uploaded_by_user_id" VARCHAR;
ALTER TABLE "org_documents" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== org_invitations ======
CREATE TABLE IF NOT EXISTS "org_invitations" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "org_id" INTEGER;
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "email" VARCHAR(255);
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "role" VARCHAR(20) DEFAULT 'driver'::character varying;
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "token" VARCHAR(100);
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "invited_by_user_id" VARCHAR;
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMP;
ALTER TABLE "org_invitations" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== org_members ======
CREATE TABLE IF NOT EXISTS "org_members" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "org_members" ADD COLUMN IF NOT EXISTS "org_id" INTEGER;
ALTER TABLE "org_members" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "org_members" ADD COLUMN IF NOT EXISTS "role" VARCHAR(20) DEFAULT 'driver'::character varying;
ALTER TABLE "org_members" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'active'::character varying;
ALTER TABLE "org_members" ADD COLUMN IF NOT EXISTS "joined_at" TIMESTAMP DEFAULT now();
ALTER TABLE "org_members" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== org_vehicles ======
CREATE TABLE IF NOT EXISTS "org_vehicles" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "org_id" INTEGER;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "assigned_driver_user_id" VARCHAR;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "make" VARCHAR(50);
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "model" VARCHAR(50);
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "year" INTEGER;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "color" VARCHAR(30);
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "license_plate" VARCHAR(20);
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "vehicle_type" VARCHAR(30) DEFAULT 'sedan'::character varying;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "seats" INTEGER DEFAULT 4;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "insurance_expiry_date" VARCHAR;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "mot_expiry_date" VARCHAR;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'active'::character varying;
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "org_vehicles" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== organizations ======
CREATE TABLE IF NOT EXISTS "organizations" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "owner_user_id" VARCHAR;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "name" VARCHAR(200);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "business_type" VARCHAR(50);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "registration_number" VARCHAR(50);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "vat_number" VARCHAR(30);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "business_address" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "business_city" VARCHAR(100);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "business_postcode" VARCHAR(15);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "business_phone" VARCHAR(20);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "business_email" VARCHAR(255);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "stripe_account_id" VARCHAR;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "logo_url" VARCHAR;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "max_drivers" INTEGER DEFAULT 20;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== pass_id_daily_counters ======
CREATE TABLE IF NOT EXISTS "pass_id_daily_counters" (bucket VARCHAR(12) PRIMARY KEY);
ALTER TABLE "pass_id_daily_counters" ADD COLUMN IF NOT EXISTS "last_seq" INTEGER DEFAULT 0;
ALTER TABLE "pass_id_daily_counters" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== password_reset_tokens ======
CREATE TABLE IF NOT EXISTS "password_reset_tokens" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "email" VARCHAR(255);
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "reset_token" TEXT;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "attempts" INTEGER DEFAULT 0;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMP;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "verified_at" TIMESTAMP;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "used_at" TIMESTAMP;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "continuation_token" TEXT;
ALTER TABLE "password_reset_tokens" ADD COLUMN IF NOT EXISTS "flow_type" VARCHAR(10) DEFAULT 'signin'::character varying;
-- ====== phone_verifications ======
CREATE TABLE IF NOT EXISTS "phone_verifications" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "phone_number" VARCHAR(20);
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "otp_code" VARCHAR(72);
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "verification_token" VARCHAR(64);
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "attempts" INTEGER DEFAULT 0;
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "expires_at" TIMESTAMP;
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "verified_at" TIMESTAMP;
ALTER TABLE "phone_verifications" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== pro_hire_negotiation_offers ======
CREATE TABLE IF NOT EXISTS "pro_hire_negotiation_offers" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "pro_hire_negotiation_offers" ADD COLUMN IF NOT EXISTS "negotiation_id" INTEGER;
ALTER TABLE "pro_hire_negotiation_offers" ADD COLUMN IF NOT EXISTS "offered_by_role" VARCHAR(20);
ALTER TABLE "pro_hire_negotiation_offers" ADD COLUMN IF NOT EXISTS "offered_by_user_id" VARCHAR;
ALTER TABLE "pro_hire_negotiation_offers" ADD COLUMN IF NOT EXISTS "amount" NUMERIC(10,2);
ALTER TABLE "pro_hire_negotiation_offers" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "pro_hire_negotiation_offers" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== pro_hire_negotiations ======
CREATE TABLE IF NOT EXISTS "pro_hire_negotiations" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "rider_id" VARCHAR;
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "pickup_location" TEXT;
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "dropoff_location" TEXT;
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "pickup_lat" NUMERIC(10,7);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "pickup_lng" NUMERIC(10,7);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "dropoff_lat" NUMERIC(10,7);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "dropoff_lng" NUMERIC(10,7);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "estimated_distance" NUMERIC(10,2);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'pending'::character varying;
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "agreed_price" NUMERIC(10,2);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "last_offer_by" VARCHAR(20);
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "ride_id" INTEGER;
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "pro_hire_negotiations" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== ratings ======
CREATE TABLE IF NOT EXISTS "ratings" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "ride_id" INTEGER;
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "rater_id" VARCHAR;
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "rated_user_id" VARCHAR;
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "rater_role" VARCHAR(20);
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "rating" INTEGER;
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "ratings" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== recurring_schedule_entries ======
CREATE TABLE IF NOT EXISTS "recurring_schedule_entries" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "schedule_id" INTEGER;
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "day_of_week" INTEGER;
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "departure_time" VARCHAR(5);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "start_location" TEXT;
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "end_location" TEXT;
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "start_lat" NUMERIC(10,7);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "start_lng" NUMERIC(10,7);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "end_lat" NUMERIC(10,7);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "end_lng" NUMERIC(10,7);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "offer_price" NUMERIC(10,2);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "max_detour_miles" NUMERIC(5,2);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "available_seats" INTEGER;
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "total_seats" INTEGER;
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "price_per_seat" NUMERIC(10,2);
ALTER TABLE "recurring_schedule_entries" ADD COLUMN IF NOT EXISTS "payment_timeout_minutes" INTEGER;
-- ====== recurring_schedules ======
CREATE TABLE IF NOT EXISTS "recurring_schedules" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "recurring_schedules" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "recurring_schedules" ADD COLUMN IF NOT EXISTS "type" VARCHAR(10);
ALTER TABLE "recurring_schedules" ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT 'active'::character varying;
ALTER TABLE "recurring_schedules" ADD COLUMN IF NOT EXISTS "last_generated_date" TIMESTAMP;
ALTER TABLE "recurring_schedules" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "recurring_schedules" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== rider_offers ======
CREATE TABLE IF NOT EXISTS "rider_offers" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "rider_id" VARCHAR;
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "pickup_location" TEXT;
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "dropoff_location" TEXT;
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "pickup_lat" NUMERIC(10,7);
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "pickup_lng" NUMERIC(10,7);
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "dropoff_lat" NUMERIC(10,7);
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "dropoff_lng" NUMERIC(10,7);
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "offer_price" NUMERIC(10,2);
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "requested_time" TIMESTAMP;
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'pending'::character varying;
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "accepted_driver_id" VARCHAR;
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
ALTER TABLE "rider_offers" ADD COLUMN IF NOT EXISTS "schedule_id" INTEGER;
-- ====== rides ======
CREATE TABLE IF NOT EXISTS "rides" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "rider_id" VARCHAR;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "pickup_location" TEXT;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "dropoff_location" TEXT;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "pickup_lat" NUMERIC(10,7);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "pickup_lng" NUMERIC(10,7);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "dropoff_lat" NUMERIC(10,7);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "dropoff_lng" NUMERIC(10,7);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "agreed_price" NUMERIC(10,2);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "scheduled_time" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'pending_payment'::character varying;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "payment_status" VARCHAR(50) DEFAULT 'pending'::character varying;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "rider_offer_id" INTEGER;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "driver_route_id" INTEGER;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "payment_deadline" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "stop_order" INTEGER;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "estimated_pickup_time" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "estimated_dropoff_time" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "actual_pickup_time" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "actual_dropoff_time" TIMESTAMP;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "payment_intent_id" VARCHAR(255);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "seats_requested" INTEGER DEFAULT 1;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "trip_message" TEXT;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "hidden_by_rider" BOOLEAN DEFAULT false;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "hidden_by_driver" BOOLEAN DEFAULT false;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "platform_fee_pence" INTEGER;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "driver_payout_pence" INTEGER;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "fee_calculation_version" VARCHAR(20);
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "fee_basis" VARCHAR(40);
-- ====== route_negotiation_offers ======
CREATE TABLE IF NOT EXISTS "route_negotiation_offers" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "route_negotiation_offers" ADD COLUMN IF NOT EXISTS "negotiation_id" INTEGER;
ALTER TABLE "route_negotiation_offers" ADD COLUMN IF NOT EXISTS "offered_by_role" VARCHAR(20);
ALTER TABLE "route_negotiation_offers" ADD COLUMN IF NOT EXISTS "offered_by_user_id" VARCHAR;
ALTER TABLE "route_negotiation_offers" ADD COLUMN IF NOT EXISTS "amount" NUMERIC(10,2);
ALTER TABLE "route_negotiation_offers" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "route_negotiation_offers" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
-- ====== route_negotiations ======
CREATE TABLE IF NOT EXISTS "route_negotiations" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "driver_route_id" INTEGER;
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "rider_id" VARCHAR;
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "driver_id" VARCHAR;
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "seats_requested" INTEGER DEFAULT 1;
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "status" VARCHAR(50) DEFAULT 'pending'::character varying;
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "agreed_price" NUMERIC(10,2);
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "last_offer_by" VARCHAR(20);
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "ride_id" INTEGER;
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "route_negotiations" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== sessions ======
CREATE TABLE IF NOT EXISTS "sessions" (sid VARCHAR PRIMARY KEY);
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "sess" JSONB;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "expire" TIMESTAMP;
-- ====== user_bank_accounts ======
CREATE TABLE IF NOT EXISTS "user_bank_accounts" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "user_bank_accounts" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "user_bank_accounts" ADD COLUMN IF NOT EXISTS "account_name" VARCHAR;
ALTER TABLE "user_bank_accounts" ADD COLUMN IF NOT EXISTS "sort_code" VARCHAR;
ALTER TABLE "user_bank_accounts" ADD COLUMN IF NOT EXISTS "account_number" VARCHAR;
ALTER TABLE "user_bank_accounts" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "user_bank_accounts" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== user_profiles ======
CREATE TABLE IF NOT EXISTS "user_profiles" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "first_name" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "last_name" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "profile_image_url" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "date_of_birth" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "phone_number" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "home_address" TEXT;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "city" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "postcode" VARCHAR;
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "user_profiles" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== user_stats ======
CREATE TABLE IF NOT EXISTS "user_stats" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "rider_rating" NUMERIC(3,2);
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "driver_rating" NUMERIC(3,2);
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "total_rides_as_rider" INTEGER DEFAULT 0;
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "total_rides_as_driver" INTEGER DEFAULT 0;
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "total_ratings_as_rider" INTEGER DEFAULT 0;
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "total_ratings_as_driver" INTEGER DEFAULT 0;
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "user_stats" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
-- ====== users ======
CREATE TABLE IF NOT EXISTS "users" (id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid());
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "first_name" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_name" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "profile_image_url" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_driver" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "driver_license_url" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "driver_verified" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "rating" NUMERIC(3,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "total_rides" INTEGER DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_customer_id" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "date_of_birth" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phone_number" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "home_address" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "city" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "postcode" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "driver_license_number" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "driver_license_expiry" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "background_check_consent" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "background_check_status" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_make" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_model" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_year" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_color" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_registration" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_insurance_expiry" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bank_account_name" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bank_sort_code" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bank_account_number" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "active_mode" VARCHAR(20);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_available" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "current_lat" NUMERIC(10,7);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "current_lng" NUMERIC(10,7);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_location_update" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "rider_rating" NUMERIC(3,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "driver_rating" NUMERIC(3,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "total_rides_as_driver" INTEGER DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "total_ratings_as_rider" INTEGER DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "total_ratings_as_driver" INTEGER DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_hash" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email_verified" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "auth_provider" VARCHAR(20) DEFAULT 'local'::character varying;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_commercial_driver" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "private_hire_license_url" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "private_hire_license_number" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dvla_check_code" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "commercial_insurance_url" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "commercial_insurance_expiry" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_inspection_url" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "vehicle_inspection_expiry" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phv_license_url" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phv_license_number" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phv_license_expiry" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "commercial_status_verified" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "username" VARCHAR(30);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "rate_per_mile" NUMERIC(5,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_online_for_hire" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "driver_tagline" VARCHAR(100);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_admin" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deleted_reason" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deleted_by" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "service_categories" TEXT[];
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tier1_max_miles" NUMERIC(6,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tier1_rate_per_mile" NUMERIC(5,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tier2_max_miles" NUMERIC(6,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tier2_rate_per_mile" NUMERIC(5,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tier3_rate_per_mile" NUMERIC(5,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "base_minimum_fare" NUMERIC(6,2);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "terms_accepted_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "privacy_accepted_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "pass_id" VARCHAR(20);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "licensing_council" VARCHAR(100);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dbs_certificate_number" VARCHAR(20);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dbs_certificate_issue_date" DATE;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dbs_certificate_expiry" DATE;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dbs_certificate_url" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dbs_update_service_subscribed" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dvla_check_status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dvla_last_checked_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "hire_reward_insurance_url" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "hire_reward_insurance_expiry" DATE;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "hire_reward_insurance_verified" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "kyc_status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "kyc_verified_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "kyc_provider" VARCHAR(40);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "sanctions_screening_status" VARCHAR(20) DEFAULT 'pending'::character varying;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "sanctions_screened_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tax_self_employment_acknowledged" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tax_acknowledged_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_connect_account_id" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_connect_onboarded" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_connect_charges_enabled" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_connect_payouts_enabled" BOOLEAN DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_connect_requirements_due" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_connect_updated_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_identity_session_id" VARCHAR;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_identity_last_attempt_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_identity_failure_reason" VARCHAR(200);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "timezone" VARCHAR(64);
-- ====== vehicles ======
CREATE TABLE IF NOT EXISTS "vehicles" (id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "make" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "model" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "year" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "color" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "registration" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "insurance_expiry" VARCHAR;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "is_primary" BOOLEAN DEFAULT true;
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT now();
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS driver_availability_user_id_unique ON public.driver_availability USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS driver_commercial_user_id_unique ON public.driver_commercial USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS driver_payouts_one_active_per_ride ON public.driver_payouts USING btree (ride_id) WHERE ((status)::text = ANY ((ARRAY['pending'::character varying, 'transferred'::character varying])::text[]));
CREATE UNIQUE INDEX IF NOT EXISTS driver_profiles_user_id_unique ON public.driver_profiles USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_orgdoc_org ON public.org_documents USING btree (org_id);
CREATE INDEX IF NOT EXISTS idx_orgdoc_type ON public.org_documents USING btree (document_type);
CREATE INDEX IF NOT EXISTS idx_orginvite_email ON public.org_invitations USING btree (email);
CREATE INDEX IF NOT EXISTS idx_orginvite_org ON public.org_invitations USING btree (org_id);
CREATE INDEX IF NOT EXISTS idx_orginvite_status ON public.org_invitations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_orginvite_token ON public.org_invitations USING btree (token);
CREATE INDEX IF NOT EXISTS idx_orgmember_org ON public.org_members USING btree (org_id);
CREATE INDEX IF NOT EXISTS idx_orgmember_status ON public.org_members USING btree (status);
CREATE INDEX IF NOT EXISTS idx_orgmember_user ON public.org_members USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_orgvehicle_driver ON public.org_vehicles USING btree (assigned_driver_user_id);
CREATE INDEX IF NOT EXISTS idx_orgvehicle_org ON public.org_vehicles USING btree (org_id);
CREATE INDEX IF NOT EXISTS idx_orgvehicle_status ON public.org_vehicles USING btree (status);
CREATE INDEX IF NOT EXISTS idx_org_owner ON public.organizations USING btree (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_org_status ON public.organizations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_recentry_day ON public.recurring_schedule_entries USING btree (day_of_week);
CREATE INDEX IF NOT EXISTS idx_recentry_schedule ON public.recurring_schedule_entries USING btree (schedule_id);
CREATE INDEX IF NOT EXISTS idx_recsched_status ON public.recurring_schedules USING btree (status);
CREATE INDEX IF NOT EXISTS idx_recsched_type ON public.recurring_schedules USING btree (type);
CREATE INDEX IF NOT EXISTS idx_recsched_user ON public.recurring_schedules USING btree (user_id);
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON public.sessions USING btree (expire);
CREATE UNIQUE INDEX IF NOT EXISTS user_bank_accounts_user_id_unique ON public.user_bank_accounts USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_user_id_unique ON public.user_profiles USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_stats_user_id_unique ON public.user_stats USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON public.users USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS users_pass_id_unique ON public.users USING btree (pass_id);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON public.users USING btree (username);

-- Chat 10/10 (May 2026): per-message clientId dedup, status/receipts, reactions, location messages
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "client_id" VARCHAR(64);
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "status" VARCHAR(16) NOT NULL DEFAULT 'sent';
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "message_type" VARCHAR(16) NOT NULL DEFAULT 'text';
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "location_lat" NUMERIC(10,7);
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "location_lng" NUMERIC(10,7);
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "reactions" JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "delivered_at" TIMESTAMP;
ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "read_at" TIMESTAMP;
CREATE INDEX IF NOT EXISTS chat_messages_ride_created_idx ON public.chat_messages USING btree (ride_id, created_at);
CREATE INDEX IF NOT EXISTS chat_messages_receiver_read_idx ON public.chat_messages USING btree (receiver_id, read);
CREATE UNIQUE INDEX IF NOT EXISTS chat_messages_ride_sender_client_uniq ON public.chat_messages USING btree (ride_id, sender_id, client_id);
COMMIT;